# Generated by Django 4.1.4 on 2023-01-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_product_delete_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
    ]
