# Generated by Django 4.1.4 on 2023-01-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_category_categorys_rename_product_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
