# Generated by Django 4.1.5 on 2023-01-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_categorys_image_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='products',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='top_speed',
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
        migrations.AlterField(
            model_name='categorys',
            name='category_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categorys',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
