# Generated by Django 4.1.5 on 2023-01-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_products_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='range',
        ),
    ]
