# Generated by Django 4.1.5 on 2023-01-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_remove_products_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Categorys',
            new_name='categorys',
        ),
    ]
