# Generated by Django 4.1.4 on 2023-01-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_rename_categorys_products_categorys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categorys',
            new_name='category',
        ),
    ]
