# Generated by Django 4.1.4 on 2023-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_rename_categorys_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='slug',
            field=models.CharField(max_length=150),
        ),
    ]
