# Generated by Django 4.1.5 on 2023-01-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_remove_product_created_at_alter_categorys_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
    ]
