# Generated by Django 4.1.4 on 2023-02-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0020_products_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
