# Generated by Django 4.1.5 on 2023-02-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carosuel',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default,1=Hidden'),
        ),
    ]
