# Generated by Django 4.1.4 on 2023-02-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
