# Generated by Django 4.1.4 on 2023-02-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
