# Generated by Django 4.1.4 on 2023-02-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_product_list_delete_product1'),
        ('user_app', '0016_cartss_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartss',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.product_list'),
        ),
    ]
