# Generated by Django 4.1.5 on 2023-02-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_rename_prifilepic_myuser_dp_remove_myuser_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartss',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cartss',
            name='user',
        ),
    ]
