# Generated by Django 4.1.5 on 2023-02-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_hellos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hellos',
        ),
    ]
