# Generated by Django 4.1.5 on 2023-02-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0031_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
